// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/clients/transport/connect/interceptors (interfaces: IdentityResolver)
//
// Generated by this command:
//
//	mockgen -destination=mock_interceptor_resolver.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/clients/transport/connect/interceptors IdentityResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interceptors "github.com/gt-tech-ai/knowledge-engine/go/clients/transport/connect/interceptors"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityResolver is a mock of IdentityResolver interface.
type MockIdentityResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityResolverMockRecorder
	isgomock struct{}
}

// MockIdentityResolverMockRecorder is the mock recorder for MockIdentityResolver.
type MockIdentityResolverMockRecorder struct {
	mock *MockIdentityResolver
}

// NewMockIdentityResolver creates a new mock instance.
func NewMockIdentityResolver(ctrl *gomock.Controller) *MockIdentityResolver {
	mock := &MockIdentityResolver{ctrl: ctrl}
	mock.recorder = &MockIdentityResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityResolver) EXPECT() *MockIdentityResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIdentityResolver) Resolve(ctx context.Context, externalSub, orgExternalID string) (*interceptors.UserPermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, externalSub, orgExternalID)
	ret0, _ := ret[0].(*interceptors.UserPermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIdentityResolverMockRecorder) Resolve(ctx, externalSub, orgExternalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIdentityResolver)(nil).Resolve), ctx, externalSub, orgExternalID)
}
