// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: ByteCache)
//
// Generated by this command:
//
//	mockgen -destination=mock_cache.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces ByteCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockByteCache is a mock of ByteCache interface.
type MockByteCache struct {
	ctrl     *gomock.Controller
	recorder *MockByteCacheMockRecorder
	isgomock struct{}
}

// MockByteCacheMockRecorder is the mock recorder for MockByteCache.
type MockByteCacheMockRecorder struct {
	mock *MockByteCache
}

// NewMockByteCache creates a new mock instance.
func NewMockByteCache(ctrl *gomock.Controller) *MockByteCache {
	mock := &MockByteCache{ctrl: ctrl}
	mock.recorder = &MockByteCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockByteCache) EXPECT() *MockByteCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockByteCache) Delete(ctx context.Context, key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", ctx, key)
}

// Delete indicates an expected call of Delete.
func (mr *MockByteCacheMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockByteCache)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockByteCache) Get(ctx context.Context, key string) ([]byte, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockByteCacheMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockByteCache)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockByteCache) Set(ctx context.Context, key string, value []byte, ttl time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", ctx, key, value, ttl)
}

// Set indicates an expected call of Set.
func (mr *MockByteCacheMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockByteCache)(nil).Set), ctx, key, value, ttl)
}
