// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: UserProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_user_provider.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces UserProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
	isgomock struct{}
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockUserProvider) CreateOrganization(ctx context.Context, org types.OrgWrite) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockUserProviderMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockUserProvider)(nil).CreateOrganization), ctx, org)
}

// CreateUser mocks base method.
func (m *MockUserProvider) CreateUser(ctx context.Context, spec types.UserCreate) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserProviderMockRecorder) CreateUser(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserProvider)(nil).CreateUser), ctx, spec)
}

// DeleteInvitation mocks base method.
func (m *MockUserProvider) DeleteInvitation(ctx context.Context, orgExtID, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, orgExtID, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockUserProviderMockRecorder) DeleteInvitation(ctx, orgExtID, invitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockUserProvider)(nil).DeleteInvitation), ctx, orgExtID, invitationID)
}

// DeleteOrganization mocks base method.
func (m *MockUserProvider) DeleteOrganization(ctx context.Context, orgExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, orgExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockUserProviderMockRecorder) DeleteOrganization(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockUserProvider)(nil).DeleteOrganization), ctx, orgExtID)
}

// InviteMembers mocks base method.
func (m *MockUserProvider) InviteMembers(ctx context.Context, orgExtID string, invites []types.InviteInput) map[string]error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteMembers", ctx, orgExtID, invites)
	ret0, _ := ret[0].(map[string]error)
	return ret0
}

// InviteMembers indicates an expected call of InviteMembers.
func (mr *MockUserProviderMockRecorder) InviteMembers(ctx, orgExtID, invites any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMembers", reflect.TypeOf((*MockUserProvider)(nil).InviteMembers), ctx, orgExtID, invites)
}

// ListInvitations mocks base method.
func (m *MockUserProvider) ListInvitations(ctx context.Context, orgExtID string) ([]types.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx, orgExtID)
	ret0, _ := ret[0].([]types.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockUserProviderMockRecorder) ListInvitations(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockUserProvider)(nil).ListInvitations), ctx, orgExtID)
}

// ListOrganizationMembers mocks base method.
func (m *MockUserProvider) ListOrganizationMembers(ctx context.Context, orgExtID string) ([]types.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationMembers", ctx, orgExtID)
	ret0, _ := ret[0].([]types.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMembers indicates an expected call of ListOrganizationMembers.
func (mr *MockUserProviderMockRecorder) ListOrganizationMembers(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMembers", reflect.TypeOf((*MockUserProvider)(nil).ListOrganizationMembers), ctx, orgExtID)
}

// ListOrganizations mocks base method.
func (m *MockUserProvider) ListOrganizations(ctx context.Context) ([]types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockUserProviderMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockUserProvider)(nil).ListOrganizations), ctx)
}

// RemoveOrganizationMember mocks base method.
func (m *MockUserProvider) RemoveOrganizationMember(ctx context.Context, orgExtID, userExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrganizationMember", ctx, orgExtID, userExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrganizationMember indicates an expected call of RemoveOrganizationMember.
func (mr *MockUserProviderMockRecorder) RemoveOrganizationMember(ctx, orgExtID, userExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrganizationMember", reflect.TypeOf((*MockUserProvider)(nil).RemoveOrganizationMember), ctx, orgExtID, userExtID)
}

// UpdateOrganization mocks base method.
func (m *MockUserProvider) UpdateOrganization(ctx context.Context, org types.OrgWrite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockUserProviderMockRecorder) UpdateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockUserProvider)(nil).UpdateOrganization), ctx, org)
}
