// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Runnable,ToolSpec)
//
// Generated by this command:
//
//	mockgen -destination=mock_execution.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Runnable,ToolSpec
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockRunnable is a mock of Runnable interface.
type MockRunnable struct {
	ctrl     *gomock.Controller
	recorder *MockRunnableMockRecorder
	isgomock struct{}
}

// MockRunnableMockRecorder is the mock recorder for MockRunnable.
type MockRunnableMockRecorder struct {
	mock *MockRunnable
}

// NewMockRunnable creates a new mock instance.
func NewMockRunnable(ctrl *gomock.Controller) *MockRunnable {
	mock := &MockRunnable{ctrl: ctrl}
	mock.recorder = &MockRunnableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnable) EXPECT() *MockRunnableMockRecorder {
	return m.recorder
}

// Meta mocks base method.
func (m *MockRunnable) Meta() types.JobMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meta")
	ret0, _ := ret[0].(types.JobMeta)
	return ret0
}

// Meta indicates an expected call of Meta.
func (mr *MockRunnableMockRecorder) Meta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meta", reflect.TypeOf((*MockRunnable)(nil).Meta))
}

// Run mocks base method.
func (m *MockRunnable) Run(ctx context.Context) (types.StepResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(types.StepResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockRunnableMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunnable)(nil).Run), ctx)
}

// MockToolSpec is a mock of ToolSpec interface.
type MockToolSpec struct {
	ctrl     *gomock.Controller
	recorder *MockToolSpecMockRecorder
	isgomock struct{}
}

// MockToolSpecMockRecorder is the mock recorder for MockToolSpec.
type MockToolSpecMockRecorder struct {
	mock *MockToolSpec
}

// NewMockToolSpec creates a new mock instance.
func NewMockToolSpec(ctrl *gomock.Controller) *MockToolSpec {
	mock := &MockToolSpec{ctrl: ctrl}
	mock.recorder = &MockToolSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolSpec) EXPECT() *MockToolSpecMockRecorder {
	return m.recorder
}

// Binary mocks base method.
func (m *MockToolSpec) Binary() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Binary")
	ret0, _ := ret[0].(string)
	return ret0
}

// Binary indicates an expected call of Binary.
func (mr *MockToolSpecMockRecorder) Binary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Binary", reflect.TypeOf((*MockToolSpec)(nil).Binary))
}

// Cmd mocks base method.
func (m *MockToolSpec) Cmd(args ...string) (string, []string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cmd", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// Cmd indicates an expected call of Cmd.
func (mr *MockToolSpecMockRecorder) Cmd(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cmd", reflect.TypeOf((*MockToolSpec)(nil).Cmd), args...)
}

// InstallHint mocks base method.
func (m *MockToolSpec) InstallHint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallHint")
	ret0, _ := ret[0].(string)
	return ret0
}

// InstallHint indicates an expected call of InstallHint.
func (mr *MockToolSpecMockRecorder) InstallHint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallHint", reflect.TypeOf((*MockToolSpec)(nil).InstallHint))
}

// Name mocks base method.
func (m *MockToolSpec) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockToolSpecMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockToolSpec)(nil).Name))
}
