// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/clients/outbox/sqs (interfaces: API)
//
// Generated by this command:
//
//	mockgen -destination=mock_outbox_sqs_api.go -package=mocks -mock_names=API=MockOutboxSQSAPI github.com/gt-tech-ai/knowledge-engine/go/clients/outbox/sqs API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxSQSAPI is a mock of API interface.
type MockOutboxSQSAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxSQSAPIMockRecorder
	isgomock struct{}
}

// MockOutboxSQSAPIMockRecorder is the mock recorder for MockOutboxSQSAPI.
type MockOutboxSQSAPIMockRecorder struct {
	mock *MockOutboxSQSAPI
}

// NewMockOutboxSQSAPI creates a new mock instance.
func NewMockOutboxSQSAPI(ctrl *gomock.Controller) *MockOutboxSQSAPI {
	mock := &MockOutboxSQSAPI{ctrl: ctrl}
	mock.recorder = &MockOutboxSQSAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxSQSAPI) EXPECT() *MockOutboxSQSAPIMockRecorder {
	return m.recorder
}

// GetQueueUrl mocks base method.
func (m *MockOutboxSQSAPI) GetQueueUrl(ctx context.Context, in *sqs.GetQueueUrlInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetQueueUrl", varargs...)
	ret0, _ := ret[0].(*sqs.GetQueueUrlOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueUrl indicates an expected call of GetQueueUrl.
func (mr *MockOutboxSQSAPIMockRecorder) GetQueueUrl(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueUrl", reflect.TypeOf((*MockOutboxSQSAPI)(nil).GetQueueUrl), varargs...)
}

// SendMessageBatch mocks base method.
func (m *MockOutboxSQSAPI) SendMessageBatch(ctx context.Context, in *sqs.SendMessageBatchInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageBatchOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendMessageBatch", varargs...)
	ret0, _ := ret[0].(*sqs.SendMessageBatchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessageBatch indicates an expected call of SendMessageBatch.
func (mr *MockOutboxSQSAPIMockRecorder) SendMessageBatch(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageBatch", reflect.TypeOf((*MockOutboxSQSAPI)(nil).SendMessageBatch), varargs...)
}
