// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Workflow)
//
// Generated by this command:
//
//	mockgen -destination=mock_workflow.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Workflow
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkflow is a mock of Workflow interface.
type MockWorkflow[In any, Out any] struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowMockRecorder[In, Out]
	isgomock struct{}
}

// MockWorkflowMockRecorder is the mock recorder for MockWorkflow.
type MockWorkflowMockRecorder[In any, Out any] struct {
	mock *MockWorkflow[In, Out]
}

// NewMockWorkflow creates a new mock instance.
func NewMockWorkflow[In any, Out any](ctrl *gomock.Controller) *MockWorkflow[In, Out] {
	mock := &MockWorkflow[In, Out]{ctrl: ctrl}
	mock.recorder = &MockWorkflowMockRecorder[In, Out]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflow[In, Out]) EXPECT() *MockWorkflowMockRecorder[In, Out] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockWorkflow[In, Out]) Execute(ctx context.Context, input In) (Out, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(Out)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockWorkflowMockRecorder[In, Out]) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWorkflow[In, Out])(nil).Execute), ctx, input)
}
