// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: CommandRunner,CmdHook)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_command_runner.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces CommandRunner,CmdHook
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockCommandRunner) Exists(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockCommandRunnerMockRecorder) Exists(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCommandRunner)(nil).Exists), name)
}

// RequireTool mocks base method.
func (m *MockCommandRunner) RequireTool(name, installHint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireTool", name, installHint)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireTool indicates an expected call of RequireTool.
func (mr *MockCommandRunnerMockRecorder) RequireTool(name, installHint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireTool", reflect.TypeOf((*MockCommandRunner)(nil).RequireTool), name, installHint)
}

// Run mocks base method.
func (m *MockCommandRunner) Run(ctx context.Context, dir, name string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dir, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCommandRunnerMockRecorder) Run(ctx, dir, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dir, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommandRunner)(nil).Run), varargs...)
}

// RunBuffered mocks base method.
func (m *MockCommandRunner) RunBuffered(ctx context.Context, dir, name string, args ...string) interfaces.CmdResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dir, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunBuffered", varargs...)
	ret0, _ := ret[0].(interfaces.CmdResult)
	return ret0
}

// RunBuffered indicates an expected call of RunBuffered.
func (mr *MockCommandRunnerMockRecorder) RunBuffered(ctx, dir, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dir, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBuffered", reflect.TypeOf((*MockCommandRunner)(nil).RunBuffered), varargs...)
}

// RunBufferedWithEnv mocks base method.
func (m *MockCommandRunner) RunBufferedWithEnv(ctx context.Context, dir string, extraEnv []string, name string, args ...string) interfaces.CmdResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dir, extraEnv, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunBufferedWithEnv", varargs...)
	ret0, _ := ret[0].(interfaces.CmdResult)
	return ret0
}

// RunBufferedWithEnv indicates an expected call of RunBufferedWithEnv.
func (mr *MockCommandRunnerMockRecorder) RunBufferedWithEnv(ctx, dir, extraEnv, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dir, extraEnv, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBufferedWithEnv", reflect.TypeOf((*MockCommandRunner)(nil).RunBufferedWithEnv), varargs...)
}

// RunWithEnv mocks base method.
func (m *MockCommandRunner) RunWithEnv(ctx context.Context, dir string, extraEnv []string, name string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, dir, extraEnv, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithEnv", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithEnv indicates an expected call of RunWithEnv.
func (mr *MockCommandRunnerMockRecorder) RunWithEnv(ctx, dir, extraEnv, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, dir, extraEnv, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithEnv", reflect.TypeOf((*MockCommandRunner)(nil).RunWithEnv), varargs...)
}

// MockCmdHook is a mock of CmdHook interface.
type MockCmdHook struct {
	ctrl     *gomock.Controller
	recorder *MockCmdHookMockRecorder
	isgomock struct{}
}

// MockCmdHookMockRecorder is the mock recorder for MockCmdHook.
type MockCmdHookMockRecorder struct {
	mock *MockCmdHook
}

// NewMockCmdHook creates a new mock instance.
func NewMockCmdHook(ctrl *gomock.Controller) *MockCmdHook {
	mock := &MockCmdHook{ctrl: ctrl}
	mock.recorder = &MockCmdHookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCmdHook) EXPECT() *MockCmdHookMockRecorder {
	return m.recorder
}

// OnFailure mocks base method.
func (m *MockCmdHook) OnFailure(cmdStr string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFailure", cmdStr)
}

// OnFailure indicates an expected call of OnFailure.
func (mr *MockCmdHookMockRecorder) OnFailure(cmdStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFailure", reflect.TypeOf((*MockCmdHook)(nil).OnFailure), cmdStr)
}

// OnStart mocks base method.
func (m *MockCmdHook) OnStart(cmdStr string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart", cmdStr)
}

// OnStart indicates an expected call of OnStart.
func (mr *MockCmdHookMockRecorder) OnStart(cmdStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockCmdHook)(nil).OnStart), cmdStr)
}

// OnSuccess mocks base method.
func (m *MockCmdHook) OnSuccess(cmdStr string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSuccess", cmdStr)
}

// OnSuccess indicates an expected call of OnSuccess.
func (mr *MockCmdHookMockRecorder) OnSuccess(cmdStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSuccess", reflect.TypeOf((*MockCmdHook)(nil).OnSuccess), cmdStr)
}
