// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: ConnectorSource,SourceBuilder)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_connector.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces ConnectorSource,SourceBuilder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectorSource is a mock of ConnectorSource interface.
type MockConnectorSource struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorSourceMockRecorder
	isgomock struct{}
}

// MockConnectorSourceMockRecorder is the mock recorder for MockConnectorSource.
type MockConnectorSourceMockRecorder struct {
	mock *MockConnectorSource
}

// NewMockConnectorSource creates a new mock instance.
func NewMockConnectorSource(ctrl *gomock.Controller) *MockConnectorSource {
	mock := &MockConnectorSource{ctrl: ctrl}
	mock.recorder = &MockConnectorSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorSource) EXPECT() *MockConnectorSourceMockRecorder {
	return m.recorder
}

// ListPage mocks base method.
func (m *MockConnectorSource) ListPage(ctx context.Context, continuationToken string, limit int) ([]interfaces.StorageObject, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPage", ctx, continuationToken, limit)
	ret0, _ := ret[0].([]interfaces.StorageObject)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPage indicates an expected call of ListPage.
func (mr *MockConnectorSourceMockRecorder) ListPage(ctx, continuationToken, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPage", reflect.TypeOf((*MockConnectorSource)(nil).ListPage), ctx, continuationToken, limit)
}

// TestConnection mocks base method.
func (m *MockConnectorSource) TestConnection(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockConnectorSourceMockRecorder) TestConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockConnectorSource)(nil).TestConnection), ctx)
}

// MockSourceBuilder is a mock of SourceBuilder interface.
type MockSourceBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSourceBuilderMockRecorder
	isgomock struct{}
}

// MockSourceBuilderMockRecorder is the mock recorder for MockSourceBuilder.
type MockSourceBuilderMockRecorder struct {
	mock *MockSourceBuilder
}

// NewMockSourceBuilder creates a new mock instance.
func NewMockSourceBuilder(ctrl *gomock.Controller) *MockSourceBuilder {
	mock := &MockSourceBuilder{ctrl: ctrl}
	mock.recorder = &MockSourceBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceBuilder) EXPECT() *MockSourceBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockSourceBuilder) Build(ctx context.Context, cfg interfaces.SourceConfig) (interfaces.ConnectorSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, cfg)
	ret0, _ := ret[0].(interfaces.ConnectorSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockSourceBuilderMockRecorder) Build(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockSourceBuilder)(nil).Build), ctx, cfg)
}
