// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: AnyJob)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_exec_job.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces AnyJob
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAnyJob is a mock of AnyJob interface.
type MockAnyJob struct {
	ctrl     *gomock.Controller
	recorder *MockAnyJobMockRecorder
	isgomock struct{}
}

// MockAnyJobMockRecorder is the mock recorder for MockAnyJob.
type MockAnyJobMockRecorder struct {
	mock *MockAnyJob
}

// NewMockAnyJob creates a new mock instance.
func NewMockAnyJob(ctrl *gomock.Controller) *MockAnyJob {
	mock := &MockAnyJob{ctrl: ctrl}
	mock.recorder = &MockAnyJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnyJob) EXPECT() *MockAnyJobMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAnyJob) Execute(ctx context.Context, runner interfaces.CommandRunner, root string) (types.StepResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, runner, root)
	ret0, _ := ret[0].(types.StepResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockAnyJobMockRecorder) Execute(ctx, runner, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAnyJob)(nil).Execute), ctx, runner, root)
}

// Meta mocks base method.
func (m *MockAnyJob) Meta() types.JobMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meta")
	ret0, _ := ret[0].(types.JobMeta)
	return ret0
}

// Meta indicates an expected call of Meta.
func (mr *MockAnyJobMockRecorder) Meta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meta", reflect.TypeOf((*MockAnyJob)(nil).Meta))
}
