// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_service.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService[T any, P any, ID comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder[T, P, ID]
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder[T any, P any, ID comparable] struct {
	mock *MockService[T, P, ID]
}

// NewMockService creates a new mock instance.
func NewMockService[T any, P any, ID comparable](ctrl *gomock.Controller) *MockService[T, P, ID] {
	mock := &MockService[T, P, ID]{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder[T, P, ID]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService[T, P, ID]) EXPECT() *MockServiceMockRecorder[T, P, ID] {
	return m.recorder
}

// Create mocks base method.
func (m *MockService[T, P, ID]) Create(ctx context.Context, entity *T) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder[T, P, ID]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService[T, P, ID])(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockService[T, P, ID]) Delete(ctx context.Context, id ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder[T, P, ID]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService[T, P, ID])(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockService[T, P, ID]) Get(ctx context.Context, id ID) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder[T, P, ID]) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService[T, P, ID])(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockService[T, P, ID]) List(ctx context.Context, params P, page types.PageRequest) (*types.Page[T], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params, page)
	ret0, _ := ret[0].(*types.Page[T])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder[T, P, ID]) List(ctx, params, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService[T, P, ID])(nil).List), ctx, params, page)
}

// Update mocks base method.
func (m *MockService[T, P, ID]) Update(ctx context.Context, id ID, entity *T) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, entity)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder[T, P, ID]) Update(ctx, id, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService[T, P, ID])(nil).Update), ctx, id, entity)
}
