// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: AuthProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_auth.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces AuthProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthProvider is a mock of AuthProvider interface.
type MockAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthProviderMockRecorder
	isgomock struct{}
}

// MockAuthProviderMockRecorder is the mock recorder for MockAuthProvider.
type MockAuthProviderMockRecorder struct {
	mock *MockAuthProvider
}

// NewMockAuthProvider creates a new mock instance.
func NewMockAuthProvider(ctrl *gomock.Controller) *MockAuthProvider {
	mock := &MockAuthProvider{ctrl: ctrl}
	mock.recorder = &MockAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthProvider) EXPECT() *MockAuthProviderMockRecorder {
	return m.recorder
}

// HasPermission mocks base method.
func (m *MockAuthProvider) HasPermission(ctx context.Context, permission, resource string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", ctx, permission, resource)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockAuthProviderMockRecorder) HasPermission(ctx, permission, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockAuthProvider)(nil).HasPermission), ctx, permission, resource)
}

// HasRole mocks base method.
func (m *MockAuthProvider) HasRole(ctx context.Context, role string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRole", ctx, role)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasRole indicates an expected call of HasRole.
func (mr *MockAuthProviderMockRecorder) HasRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRole", reflect.TypeOf((*MockAuthProvider)(nil).HasRole), ctx, role)
}

// TenantContext mocks base method.
func (m *MockAuthProvider) TenantContext(ctx context.Context) (*types.TenantContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantContext", ctx)
	ret0, _ := ret[0].(*types.TenantContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TenantContext indicates an expected call of TenantContext.
func (mr *MockAuthProviderMockRecorder) TenantContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantContext", reflect.TypeOf((*MockAuthProvider)(nil).TenantContext), ctx)
}

// ValidateToken mocks base method.
func (m *MockAuthProvider) ValidateToken(ctx context.Context, token string) (*interfaces.AuthIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(*interfaces.AuthIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthProviderMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthProvider)(nil).ValidateToken), ctx, token)
}
