// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: LeaderElector)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_leader.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces LeaderElector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLeaderElector is a mock of LeaderElector interface.
type MockLeaderElector struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderElectorMockRecorder
	isgomock struct{}
}

// MockLeaderElectorMockRecorder is the mock recorder for MockLeaderElector.
type MockLeaderElectorMockRecorder struct {
	mock *MockLeaderElector
}

// NewMockLeaderElector creates a new mock instance.
func NewMockLeaderElector(ctrl *gomock.Controller) *MockLeaderElector {
	mock := &MockLeaderElector{ctrl: ctrl}
	mock.recorder = &MockLeaderElectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderElector) EXPECT() *MockLeaderElectorMockRecorder {
	return m.recorder
}

// IsLeader mocks base method.
func (m *MockLeaderElector) IsLeader(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLeader", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLeader indicates an expected call of IsLeader.
func (mr *MockLeaderElectorMockRecorder) IsLeader(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLeader", reflect.TypeOf((*MockLeaderElector)(nil).IsLeader), ctx)
}
