// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: StorageClient)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_storage.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces StorageClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageClient is a mock of StorageClient interface.
type MockStorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockStorageClientMockRecorder
	isgomock struct{}
}

// MockStorageClientMockRecorder is the mock recorder for MockStorageClient.
type MockStorageClientMockRecorder struct {
	mock *MockStorageClient
}

// NewMockStorageClient creates a new mock instance.
func NewMockStorageClient(ctrl *gomock.Controller) *MockStorageClient {
	mock := &MockStorageClient{ctrl: ctrl}
	mock.recorder = &MockStorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageClient) EXPECT() *MockStorageClientMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockStorageClient) AbortMultipartUpload(ctx context.Context, bucket, key, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, bucket, key, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockStorageClientMockRecorder) AbortMultipartUpload(ctx, bucket, key, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockStorageClient)(nil).AbortMultipartUpload), ctx, bucket, key, uploadID)
}

// CompleteMultipartUpload mocks base method.
func (m *MockStorageClient) CompleteMultipartUpload(ctx context.Context, bucket, key, uploadID string, parts []interfaces.CompletedPart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, bucket, key, uploadID, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockStorageClientMockRecorder) CompleteMultipartUpload(ctx, bucket, key, uploadID, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockStorageClient)(nil).CompleteMultipartUpload), ctx, bucket, key, uploadID, parts)
}

// CreateMultipartUpload mocks base method.
func (m *MockStorageClient) CreateMultipartUpload(ctx context.Context, bucket, key, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, bucket, key, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockStorageClientMockRecorder) CreateMultipartUpload(ctx, bucket, key, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockStorageClient)(nil).CreateMultipartUpload), ctx, bucket, key, contentType)
}

// Delete mocks base method.
func (m *MockStorageClient) Delete(ctx context.Context, bucket, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, bucket, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageClientMockRecorder) Delete(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageClient)(nil).Delete), ctx, bucket, key)
}

// DeleteBatch mocks base method.
func (m *MockStorageClient) DeleteBatch(ctx context.Context, bucket string, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, bucket, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockStorageClientMockRecorder) DeleteBatch(ctx, bucket, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockStorageClient)(nil).DeleteBatch), ctx, bucket, keys)
}

// Download mocks base method.
func (m *MockStorageClient) Download(ctx context.Context, bucket, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, bucket, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockStorageClientMockRecorder) Download(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStorageClient)(nil).Download), ctx, bucket, key)
}

// EnsureBucket mocks base method.
func (m *MockStorageClient) EnsureBucket(ctx context.Context, bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBucket", ctx, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureBucket indicates an expected call of EnsureBucket.
func (mr *MockStorageClientMockRecorder) EnsureBucket(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBucket", reflect.TypeOf((*MockStorageClient)(nil).EnsureBucket), ctx, bucket)
}

// Exists mocks base method.
func (m *MockStorageClient) Exists(ctx context.Context, bucket, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, bucket, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockStorageClientMockRecorder) Exists(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStorageClient)(nil).Exists), ctx, bucket, key)
}

// ListMultipartUploads mocks base method.
func (m *MockStorageClient) ListMultipartUploads(ctx context.Context, bucket string) ([]interfaces.MultipartUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMultipartUploads", ctx, bucket)
	ret0, _ := ret[0].([]interfaces.MultipartUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMultipartUploads indicates an expected call of ListMultipartUploads.
func (mr *MockStorageClientMockRecorder) ListMultipartUploads(ctx, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMultipartUploads", reflect.TypeOf((*MockStorageClient)(nil).ListMultipartUploads), ctx, bucket)
}

// ListObjects mocks base method.
func (m *MockStorageClient) ListObjects(ctx context.Context, bucket, prefix string) ([]interfaces.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, bucket, prefix)
	ret0, _ := ret[0].([]interfaces.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockStorageClientMockRecorder) ListObjects(ctx, bucket, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockStorageClient)(nil).ListObjects), ctx, bucket, prefix)
}

// ListObjectsPage mocks base method.
func (m *MockStorageClient) ListObjectsPage(ctx context.Context, bucket, prefix string, limit int) ([]interfaces.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsPage", ctx, bucket, prefix, limit)
	ret0, _ := ret[0].([]interfaces.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsPage indicates an expected call of ListObjectsPage.
func (mr *MockStorageClientMockRecorder) ListObjectsPage(ctx, bucket, prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsPage", reflect.TypeOf((*MockStorageClient)(nil).ListObjectsPage), ctx, bucket, prefix, limit)
}

// ListObjectsPageToken mocks base method.
func (m *MockStorageClient) ListObjectsPageToken(ctx context.Context, bucket, prefix, continuationToken string, limit int) ([]interfaces.StorageObject, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsPageToken", ctx, bucket, prefix, continuationToken, limit)
	ret0, _ := ret[0].([]interfaces.StorageObject)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListObjectsPageToken indicates an expected call of ListObjectsPageToken.
func (mr *MockStorageClientMockRecorder) ListObjectsPageToken(ctx, bucket, prefix, continuationToken, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsPageToken", reflect.TypeOf((*MockStorageClient)(nil).ListObjectsPageToken), ctx, bucket, prefix, continuationToken, limit)
}

// PresignPutURL mocks base method.
func (m *MockStorageClient) PresignPutURL(ctx context.Context, bucket, key string, expirySeconds int, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPutURL", ctx, bucket, key, expirySeconds, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutURL indicates an expected call of PresignPutURL.
func (mr *MockStorageClientMockRecorder) PresignPutURL(ctx, bucket, key, expirySeconds, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutURL", reflect.TypeOf((*MockStorageClient)(nil).PresignPutURL), ctx, bucket, key, expirySeconds, contentType)
}

// PresignURL mocks base method.
func (m *MockStorageClient) PresignURL(ctx context.Context, bucket, key string, expirySeconds int, displayFilename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignURL", ctx, bucket, key, expirySeconds, displayFilename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignURL indicates an expected call of PresignURL.
func (mr *MockStorageClientMockRecorder) PresignURL(ctx, bucket, key, expirySeconds, displayFilename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignURL", reflect.TypeOf((*MockStorageClient)(nil).PresignURL), ctx, bucket, key, expirySeconds, displayFilename)
}

// PresignUploadPart mocks base method.
func (m *MockStorageClient) PresignUploadPart(ctx context.Context, bucket, key, uploadID string, partNumber int32, expirySeconds int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignUploadPart", ctx, bucket, key, uploadID, partNumber, expirySeconds)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignUploadPart indicates an expected call of PresignUploadPart.
func (mr *MockStorageClientMockRecorder) PresignUploadPart(ctx, bucket, key, uploadID, partNumber, expirySeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignUploadPart", reflect.TypeOf((*MockStorageClient)(nil).PresignUploadPart), ctx, bucket, key, uploadID, partNumber, expirySeconds)
}

// Stat mocks base method.
func (m *MockStorageClient) Stat(ctx context.Context, bucket, key string) (interfaces.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, bucket, key)
	ret0, _ := ret[0].(interfaces.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockStorageClientMockRecorder) Stat(ctx, bucket, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockStorageClient)(nil).Stat), ctx, bucket, key)
}

// Upload mocks base method.
func (m *MockStorageClient) Upload(ctx context.Context, bucket, key string, body io.Reader, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, bucket, key, body, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageClientMockRecorder) Upload(ctx, bucket, key, body, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorageClient)(nil).Upload), ctx, bucket, key, body, contentType)
}
