// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-sdk-go-v2/credentials/stscreds (interfaces: AssumeRoleAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_sts_assume_role.go -package=mocks github.com/aws/aws-sdk-go-v2/credentials/stscreds AssumeRoleAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	gomock "go.uber.org/mock/gomock"
)

// MockAssumeRoleAPIClient is a mock of AssumeRoleAPIClient interface.
type MockAssumeRoleAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAssumeRoleAPIClientMockRecorder
	isgomock struct{}
}

// MockAssumeRoleAPIClientMockRecorder is the mock recorder for MockAssumeRoleAPIClient.
type MockAssumeRoleAPIClientMockRecorder struct {
	mock *MockAssumeRoleAPIClient
}

// NewMockAssumeRoleAPIClient creates a new mock instance.
func NewMockAssumeRoleAPIClient(ctrl *gomock.Controller) *MockAssumeRoleAPIClient {
	mock := &MockAssumeRoleAPIClient{ctrl: ctrl}
	mock.recorder = &MockAssumeRoleAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssumeRoleAPIClient) EXPECT() *MockAssumeRoleAPIClientMockRecorder {
	return m.recorder
}

// AssumeRole mocks base method.
func (m *MockAssumeRoleAPIClient) AssumeRole(ctx context.Context, params *sts.AssumeRoleInput, optFns ...func(*sts.Options)) (*sts.AssumeRoleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AssumeRole", varargs...)
	ret0, _ := ret[0].(*sts.AssumeRoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssumeRole indicates an expected call of AssumeRole.
func (mr *MockAssumeRoleAPIClientMockRecorder) AssumeRole(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssumeRole", reflect.TypeOf((*MockAssumeRoleAPIClient)(nil).AssumeRole), varargs...)
}
