// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: OutboxStore,OutboxSink)
//
// Generated by this command:
//
//	mockgen -destination=mock_outbox.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces OutboxStore,OutboxSink
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxStore is a mock of OutboxStore interface.
type MockOutboxStore struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxStoreMockRecorder
	isgomock struct{}
}

// MockOutboxStoreMockRecorder is the mock recorder for MockOutboxStore.
type MockOutboxStoreMockRecorder struct {
	mock *MockOutboxStore
}

// NewMockOutboxStore creates a new mock instance.
func NewMockOutboxStore(ctrl *gomock.Controller) *MockOutboxStore {
	mock := &MockOutboxStore{ctrl: ctrl}
	mock.recorder = &MockOutboxStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxStore) EXPECT() *MockOutboxStoreMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MockOutboxStore) Claim(ctx context.Context, lane string, limit int) ([]types.OutboxRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, lane, limit)
	ret0, _ := ret[0].([]types.OutboxRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockOutboxStoreMockRecorder) Claim(ctx, lane, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockOutboxStore)(nil).Claim), ctx, lane, limit)
}

// MarkSent mocks base method.
func (m *MockOutboxStore) MarkSent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockOutboxStoreMockRecorder) MarkSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockOutboxStore)(nil).MarkSent), ctx, id)
}

// Park mocks base method.
func (m *MockOutboxStore) Park(ctx context.Context, id uuid.UUID, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Park", ctx, id, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Park indicates an expected call of Park.
func (mr *MockOutboxStoreMockRecorder) Park(ctx, id, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Park", reflect.TypeOf((*MockOutboxStore)(nil).Park), ctx, id, lastErr)
}

// Retry mocks base method.
func (m *MockOutboxStore) Retry(ctx context.Context, id uuid.UUID, next time.Time, lastErr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", ctx, id, next, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockOutboxStoreMockRecorder) Retry(ctx, id, next, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockOutboxStore)(nil).Retry), ctx, id, next, lastErr)
}

// Stats mocks base method.
func (m *MockOutboxStore) Stats(ctx context.Context, lane string) (types.OutboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, lane)
	ret0, _ := ret[0].(types.OutboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockOutboxStoreMockRecorder) Stats(ctx, lane any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockOutboxStore)(nil).Stats), ctx, lane)
}

// MockOutboxSink is a mock of OutboxSink interface.
type MockOutboxSink struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxSinkMockRecorder
	isgomock struct{}
}

// MockOutboxSinkMockRecorder is the mock recorder for MockOutboxSink.
type MockOutboxSinkMockRecorder struct {
	mock *MockOutboxSink
}

// NewMockOutboxSink creates a new mock instance.
func NewMockOutboxSink(ctrl *gomock.Controller) *MockOutboxSink {
	mock := &MockOutboxSink{ctrl: ctrl}
	mock.recorder = &MockOutboxSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxSink) EXPECT() *MockOutboxSinkMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockOutboxSink) Send(ctx context.Context, recs []types.OutboxRecord) []error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, recs)
	ret0, _ := ret[0].([]error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockOutboxSinkMockRecorder) Send(ctx, recs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOutboxSink)(nil).Send), ctx, recs)
}
