// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: ReplayBuffer)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_replaybuffer.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces ReplayBuffer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockReplayBuffer is a mock of ReplayBuffer interface.
type MockReplayBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockReplayBufferMockRecorder
	isgomock struct{}
}

// MockReplayBufferMockRecorder is the mock recorder for MockReplayBuffer.
type MockReplayBufferMockRecorder struct {
	mock *MockReplayBuffer
}

// NewMockReplayBuffer creates a new mock instance.
func NewMockReplayBuffer(ctrl *gomock.Controller) *MockReplayBuffer {
	mock := &MockReplayBuffer{ctrl: ctrl}
	mock.recorder = &MockReplayBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplayBuffer) EXPECT() *MockReplayBufferMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockReplayBuffer) Append(ctx context.Context, key, msgID string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, key, msgID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockReplayBufferMockRecorder) Append(ctx, key, msgID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockReplayBuffer)(nil).Append), ctx, key, msgID, payload)
}

// Delete mocks base method.
func (m *MockReplayBuffer) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReplayBufferMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReplayBuffer)(nil).Delete), ctx, key)
}

// Prune mocks base method.
func (m *MockReplayBuffer) Prune(ctx context.Context, key, upToMsgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, key, upToMsgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune.
func (mr *MockReplayBufferMockRecorder) Prune(ctx, key, upToMsgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockReplayBuffer)(nil).Prune), ctx, key, upToMsgID)
}

// ReplayAfter mocks base method.
func (m *MockReplayBuffer) ReplayAfter(ctx context.Context, key, afterMsgID string) ([]interfaces.BufferedMessage, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplayAfter", ctx, key, afterMsgID)
	ret0, _ := ret[0].([]interfaces.BufferedMessage)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReplayAfter indicates an expected call of ReplayAfter.
func (mr *MockReplayBufferMockRecorder) ReplayAfter(ctx, key, afterMsgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplayAfter", reflect.TypeOf((*MockReplayBuffer)(nil).ReplayAfter), ctx, key, afterMsgID)
}
