// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/clients/auth/auth0 (interfaces: OrgPager,MemberPager,OrgWriter,Inviter,MemberRoleLister,UserProvisioner)
//
// Generated by this command:
//
//	mockgen -destination=mock_auth0_seams.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/clients/auth/auth0 OrgPager,MemberPager,OrgWriter,Inviter,MemberRoleLister,UserProvisioner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth0 "github.com/gt-tech-ai/knowledge-engine/go/clients/auth/auth0"
	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgPager is a mock of OrgPager interface.
type MockOrgPager struct {
	ctrl     *gomock.Controller
	recorder *MockOrgPagerMockRecorder
	isgomock struct{}
}

// MockOrgPagerMockRecorder is the mock recorder for MockOrgPager.
type MockOrgPagerMockRecorder struct {
	mock *MockOrgPager
}

// NewMockOrgPager creates a new mock instance.
func NewMockOrgPager(ctrl *gomock.Controller) *MockOrgPager {
	mock := &MockOrgPager{ctrl: ctrl}
	mock.recorder = &MockOrgPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgPager) EXPECT() *MockOrgPagerMockRecorder {
	return m.recorder
}

// ListOrgPage mocks base method.
func (m *MockOrgPager) ListOrgPage(ctx context.Context, cursor *string) ([]auth0.RawOrg, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgPage", ctx, cursor)
	ret0, _ := ret[0].([]auth0.RawOrg)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrgPage indicates an expected call of ListOrgPage.
func (mr *MockOrgPagerMockRecorder) ListOrgPage(ctx, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgPage", reflect.TypeOf((*MockOrgPager)(nil).ListOrgPage), ctx, cursor)
}

// MockMemberPager is a mock of MemberPager interface.
type MockMemberPager struct {
	ctrl     *gomock.Controller
	recorder *MockMemberPagerMockRecorder
	isgomock struct{}
}

// MockMemberPagerMockRecorder is the mock recorder for MockMemberPager.
type MockMemberPagerMockRecorder struct {
	mock *MockMemberPager
}

// NewMockMemberPager creates a new mock instance.
func NewMockMemberPager(ctrl *gomock.Controller) *MockMemberPager {
	mock := &MockMemberPager{ctrl: ctrl}
	mock.recorder = &MockMemberPagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberPager) EXPECT() *MockMemberPagerMockRecorder {
	return m.recorder
}

// ListMemberPage mocks base method.
func (m *MockMemberPager) ListMemberPage(ctx context.Context, orgExtID string, cursor *string) ([]auth0.RawMember, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberPage", ctx, orgExtID, cursor)
	ret0, _ := ret[0].([]auth0.RawMember)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMemberPage indicates an expected call of ListMemberPage.
func (mr *MockMemberPagerMockRecorder) ListMemberPage(ctx, orgExtID, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberPage", reflect.TypeOf((*MockMemberPager)(nil).ListMemberPage), ctx, orgExtID, cursor)
}

// MockOrgWriter is a mock of OrgWriter interface.
type MockOrgWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOrgWriterMockRecorder
	isgomock struct{}
}

// MockOrgWriterMockRecorder is the mock recorder for MockOrgWriter.
type MockOrgWriterMockRecorder struct {
	mock *MockOrgWriter
}

// NewMockOrgWriter creates a new mock instance.
func NewMockOrgWriter(ctrl *gomock.Controller) *MockOrgWriter {
	mock := &MockOrgWriter{ctrl: ctrl}
	mock.recorder = &MockOrgWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgWriter) EXPECT() *MockOrgWriterMockRecorder {
	return m.recorder
}

// CreateOrg mocks base method.
func (m *MockOrgWriter) CreateOrg(ctx context.Context, org types.OrgWrite) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrg", ctx, org)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrg indicates an expected call of CreateOrg.
func (mr *MockOrgWriterMockRecorder) CreateOrg(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrg", reflect.TypeOf((*MockOrgWriter)(nil).CreateOrg), ctx, org)
}

// DeleteOrg mocks base method.
func (m *MockOrgWriter) DeleteOrg(ctx context.Context, orgExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrg", ctx, orgExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrg indicates an expected call of DeleteOrg.
func (mr *MockOrgWriterMockRecorder) DeleteOrg(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrg", reflect.TypeOf((*MockOrgWriter)(nil).DeleteOrg), ctx, orgExtID)
}

// UpdateOrg mocks base method.
func (m *MockOrgWriter) UpdateOrg(ctx context.Context, org types.OrgWrite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrg", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrg indicates an expected call of UpdateOrg.
func (mr *MockOrgWriterMockRecorder) UpdateOrg(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrg", reflect.TypeOf((*MockOrgWriter)(nil).UpdateOrg), ctx, org)
}

// MockInviter is a mock of Inviter interface.
type MockInviter struct {
	ctrl     *gomock.Controller
	recorder *MockInviterMockRecorder
	isgomock struct{}
}

// MockInviterMockRecorder is the mock recorder for MockInviter.
type MockInviterMockRecorder struct {
	mock *MockInviter
}

// NewMockInviter creates a new mock instance.
func NewMockInviter(ctrl *gomock.Controller) *MockInviter {
	mock := &MockInviter{ctrl: ctrl}
	mock.recorder = &MockInviterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviter) EXPECT() *MockInviterMockRecorder {
	return m.recorder
}

// CreateInvitation mocks base method.
func (m *MockInviter) CreateInvitation(ctx context.Context, orgExtID string, inv types.InviteInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, orgExtID, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockInviterMockRecorder) CreateInvitation(ctx, orgExtID, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockInviter)(nil).CreateInvitation), ctx, orgExtID, inv)
}

// DeleteInvitation mocks base method.
func (m *MockInviter) DeleteInvitation(ctx context.Context, orgExtID, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, orgExtID, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockInviterMockRecorder) DeleteInvitation(ctx, orgExtID, invitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockInviter)(nil).DeleteInvitation), ctx, orgExtID, invitationID)
}

// ListInvitations mocks base method.
func (m *MockInviter) ListInvitations(ctx context.Context, orgExtID string) ([]types.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx, orgExtID)
	ret0, _ := ret[0].([]types.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockInviterMockRecorder) ListInvitations(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockInviter)(nil).ListInvitations), ctx, orgExtID)
}

// RemoveMember mocks base method.
func (m *MockInviter) RemoveMember(ctx context.Context, orgExtID, userExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, orgExtID, userExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockInviterMockRecorder) RemoveMember(ctx, orgExtID, userExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockInviter)(nil).RemoveMember), ctx, orgExtID, userExtID)
}

// MockMemberRoleLister is a mock of MemberRoleLister interface.
type MockMemberRoleLister struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRoleListerMockRecorder
	isgomock struct{}
}

// MockMemberRoleListerMockRecorder is the mock recorder for MockMemberRoleLister.
type MockMemberRoleListerMockRecorder struct {
	mock *MockMemberRoleLister
}

// NewMockMemberRoleLister creates a new mock instance.
func NewMockMemberRoleLister(ctrl *gomock.Controller) *MockMemberRoleLister {
	mock := &MockMemberRoleLister{ctrl: ctrl}
	mock.recorder = &MockMemberRoleListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRoleLister) EXPECT() *MockMemberRoleListerMockRecorder {
	return m.recorder
}

// ListMemberRoles mocks base method.
func (m *MockMemberRoleLister) ListMemberRoles(ctx context.Context, orgExtID, userSub string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberRoles", ctx, orgExtID, userSub)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberRoles indicates an expected call of ListMemberRoles.
func (mr *MockMemberRoleListerMockRecorder) ListMemberRoles(ctx, orgExtID, userSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberRoles", reflect.TypeOf((*MockMemberRoleLister)(nil).ListMemberRoles), ctx, orgExtID, userSub)
}

// MockUserProvisioner is a mock of UserProvisioner interface.
type MockUserProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockUserProvisionerMockRecorder
	isgomock struct{}
}

// MockUserProvisionerMockRecorder is the mock recorder for MockUserProvisioner.
type MockUserProvisionerMockRecorder struct {
	mock *MockUserProvisioner
}

// NewMockUserProvisioner creates a new mock instance.
func NewMockUserProvisioner(ctrl *gomock.Controller) *MockUserProvisioner {
	mock := &MockUserProvisioner{ctrl: ctrl}
	mock.recorder = &MockUserProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvisioner) EXPECT() *MockUserProvisionerMockRecorder {
	return m.recorder
}

// AssignRoles mocks base method.
func (m *MockUserProvisioner) AssignRoles(ctx context.Context, userID string, roleIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoles", ctx, userID, roleIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoles indicates an expected call of AssignRoles.
func (mr *MockUserProvisionerMockRecorder) AssignRoles(ctx, userID, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoles", reflect.TypeOf((*MockUserProvisioner)(nil).AssignRoles), ctx, userID, roleIDs)
}

// CreateUser mocks base method.
func (m *MockUserProvisioner) CreateUser(ctx context.Context, spec types.UserCreate) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserProvisionerMockRecorder) CreateUser(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserProvisioner)(nil).CreateUser), ctx, spec)
}

// UserIDByEmail mocks base method.
func (m *MockUserProvisioner) UserIDByEmail(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDByEmail", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDByEmail indicates an expected call of UserIDByEmail.
func (mr *MockUserProvisionerMockRecorder) UserIDByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDByEmail", reflect.TypeOf((*MockUserProvisioner)(nil).UserIDByEmail), ctx, email)
}
