// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/clients/outbox/s3 (interfaces: API)
//
// Generated by this command:
//
//	mockgen -destination=mock_outbox_s3_api.go -package=mocks -mock_names=API=MockOutboxS3API github.com/gt-tech-ai/knowledge-engine/go/clients/outbox/s3 API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxS3API is a mock of API interface.
type MockOutboxS3API struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxS3APIMockRecorder
	isgomock struct{}
}

// MockOutboxS3APIMockRecorder is the mock recorder for MockOutboxS3API.
type MockOutboxS3APIMockRecorder struct {
	mock *MockOutboxS3API
}

// NewMockOutboxS3API creates a new mock instance.
func NewMockOutboxS3API(ctrl *gomock.Controller) *MockOutboxS3API {
	mock := &MockOutboxS3API{ctrl: ctrl}
	mock.recorder = &MockOutboxS3APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxS3API) EXPECT() *MockOutboxS3APIMockRecorder {
	return m.recorder
}

// PutObject mocks base method.
func (m *MockOutboxS3API) PutObject(ctx context.Context, in *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockOutboxS3APIMockRecorder) PutObject(ctx, in any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockOutboxS3API)(nil).PutObject), varargs...)
}
