// Code generated by MockGen. DO NOT EDIT.
// Source: connectrpc.com/connect (interfaces: StreamingHandlerConn)
//
// Generated by this command:
//
//	mockgen -destination=../../../../tests/mocks/mock_stream_conn.go -package=mocks connectrpc.com/connect StreamingHandlerConn
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	connect "connectrpc.com/connect"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamingHandlerConn is a mock of StreamingHandlerConn interface.
type MockStreamingHandlerConn struct {
	ctrl     *gomock.Controller
	recorder *MockStreamingHandlerConnMockRecorder
	isgomock struct{}
}

// MockStreamingHandlerConnMockRecorder is the mock recorder for MockStreamingHandlerConn.
type MockStreamingHandlerConnMockRecorder struct {
	mock *MockStreamingHandlerConn
}

// NewMockStreamingHandlerConn creates a new mock instance.
func NewMockStreamingHandlerConn(ctrl *gomock.Controller) *MockStreamingHandlerConn {
	mock := &MockStreamingHandlerConn{ctrl: ctrl}
	mock.recorder = &MockStreamingHandlerConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamingHandlerConn) EXPECT() *MockStreamingHandlerConnMockRecorder {
	return m.recorder
}

// Peer mocks base method.
func (m *MockStreamingHandlerConn) Peer() connect.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peer")
	ret0, _ := ret[0].(connect.Peer)
	return ret0
}

// Peer indicates an expected call of Peer.
func (mr *MockStreamingHandlerConnMockRecorder) Peer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peer", reflect.TypeOf((*MockStreamingHandlerConn)(nil).Peer))
}

// Receive mocks base method.
func (m *MockStreamingHandlerConn) Receive(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Receive indicates an expected call of Receive.
func (mr *MockStreamingHandlerConnMockRecorder) Receive(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockStreamingHandlerConn)(nil).Receive), arg0)
}

// RequestHeader mocks base method.
func (m *MockStreamingHandlerConn) RequestHeader() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestHeader")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// RequestHeader indicates an expected call of RequestHeader.
func (mr *MockStreamingHandlerConnMockRecorder) RequestHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestHeader", reflect.TypeOf((*MockStreamingHandlerConn)(nil).RequestHeader))
}

// ResponseHeader mocks base method.
func (m *MockStreamingHandlerConn) ResponseHeader() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseHeader")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// ResponseHeader indicates an expected call of ResponseHeader.
func (mr *MockStreamingHandlerConnMockRecorder) ResponseHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseHeader", reflect.TypeOf((*MockStreamingHandlerConn)(nil).ResponseHeader))
}

// ResponseTrailer mocks base method.
func (m *MockStreamingHandlerConn) ResponseTrailer() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseTrailer")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// ResponseTrailer indicates an expected call of ResponseTrailer.
func (mr *MockStreamingHandlerConnMockRecorder) ResponseTrailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseTrailer", reflect.TypeOf((*MockStreamingHandlerConn)(nil).ResponseTrailer))
}

// Send mocks base method.
func (m *MockStreamingHandlerConn) Send(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamingHandlerConnMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStreamingHandlerConn)(nil).Send), arg0)
}

// Spec mocks base method.
func (m *MockStreamingHandlerConn) Spec() connect.Spec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spec")
	ret0, _ := ret[0].(connect.Spec)
	return ret0
}

// Spec indicates an expected call of Spec.
func (mr *MockStreamingHandlerConnMockRecorder) Spec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spec", reflect.TypeOf((*MockStreamingHandlerConn)(nil).Spec))
}
