// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: CacheInvalidator)
//
// Generated by this command:
//
//	mockgen -destination=mock_cache_invalidator.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces CacheInvalidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheInvalidator is a mock of CacheInvalidator interface.
type MockCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockCacheInvalidatorMockRecorder is the mock recorder for MockCacheInvalidator.
type MockCacheInvalidatorMockRecorder struct {
	mock *MockCacheInvalidator
}

// NewMockCacheInvalidator creates a new mock instance.
func NewMockCacheInvalidator(ctrl *gomock.Controller) *MockCacheInvalidator {
	mock := &MockCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheInvalidator) EXPECT() *MockCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateAll mocks base method.
func (m *MockCacheInvalidator) InvalidateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAll indicates an expected call of InvalidateAll.
func (mr *MockCacheInvalidatorMockRecorder) InvalidateAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAll", reflect.TypeOf((*MockCacheInvalidator)(nil).InvalidateAll), ctx)
}

// InvalidatePrefix mocks base method.
func (m *MockCacheInvalidator) InvalidatePrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidatePrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidatePrefix indicates an expected call of InvalidatePrefix.
func (mr *MockCacheInvalidatorMockRecorder) InvalidatePrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidatePrefix", reflect.TypeOf((*MockCacheInvalidator)(nil).InvalidatePrefix), ctx, prefix)
}
