// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Pipeline)
//
// Generated by this command:
//
//	mockgen -destination=mock_pipeline.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Pipeline
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPipeline is a mock of Pipeline interface.
type MockPipeline[In any, Out any] struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineMockRecorder[In, Out]
	isgomock struct{}
}

// MockPipelineMockRecorder is the mock recorder for MockPipeline.
type MockPipelineMockRecorder[In any, Out any] struct {
	mock *MockPipeline[In, Out]
}

// NewMockPipeline creates a new mock instance.
func NewMockPipeline[In any, Out any](ctrl *gomock.Controller) *MockPipeline[In, Out] {
	mock := &MockPipeline[In, Out]{ctrl: ctrl}
	mock.recorder = &MockPipelineMockRecorder[In, Out]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipeline[In, Out]) EXPECT() *MockPipelineMockRecorder[In, Out] {
	return m.recorder
}

// Execute mocks base method.
func (m *MockPipeline[In, Out]) Execute(ctx context.Context, input In) (Out, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(Out)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockPipelineMockRecorder[In, Out]) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockPipeline[In, Out])(nil).Execute), ctx, input)
}
