// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/clients/prometheus (interfaces: HTTPDoer)
//
// Generated by this command:
//
//	mockgen -destination=mock_prometheus_http_doer.go -package=mocks -mock_names=HTTPDoer=MockPrometheusHTTPDoer github.com/gt-tech-ai/knowledge-engine/go/clients/prometheus HTTPDoer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrometheusHTTPDoer is a mock of HTTPDoer interface.
type MockPrometheusHTTPDoer struct {
	ctrl     *gomock.Controller
	recorder *MockPrometheusHTTPDoerMockRecorder
	isgomock struct{}
}

// MockPrometheusHTTPDoerMockRecorder is the mock recorder for MockPrometheusHTTPDoer.
type MockPrometheusHTTPDoerMockRecorder struct {
	mock *MockPrometheusHTTPDoer
}

// NewMockPrometheusHTTPDoer creates a new mock instance.
func NewMockPrometheusHTTPDoer(ctrl *gomock.Controller) *MockPrometheusHTTPDoer {
	mock := &MockPrometheusHTTPDoer{ctrl: ctrl}
	mock.recorder = &MockPrometheusHTTPDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrometheusHTTPDoer) EXPECT() *MockPrometheusHTTPDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockPrometheusHTTPDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockPrometheusHTTPDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockPrometheusHTTPDoer)(nil).Do), req)
}
