// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Job,Worker,JobEnqueuer,JobScheduler,WorkerRegistry)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_jobs.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Job,Worker,JobEnqueuer,JobScheduler,WorkerRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockJob is a mock of Job interface.
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder
	isgomock struct{}
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder struct {
	mock *MockJob
}

// NewMockJob creates a new mock instance.
func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob) EXPECT() *MockJobMockRecorder {
	return m.recorder
}

// Args mocks base method.
func (m *MockJob) Args() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Args")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Args indicates an expected call of Args.
func (mr *MockJobMockRecorder) Args() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Args", reflect.TypeOf((*MockJob)(nil).Args))
}

// Kind mocks base method.
func (m *MockJob) Kind() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(string)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockJobMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockJob)(nil).Kind))
}

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// Work mocks base method.
func (m *MockWorker) Work(args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Work", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Work indicates an expected call of Work.
func (mr *MockWorkerMockRecorder) Work(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Work", reflect.TypeOf((*MockWorker)(nil).Work), args)
}

// MockJobEnqueuer is a mock of JobEnqueuer interface.
type MockJobEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockJobEnqueuerMockRecorder
	isgomock struct{}
}

// MockJobEnqueuerMockRecorder is the mock recorder for MockJobEnqueuer.
type MockJobEnqueuerMockRecorder struct {
	mock *MockJobEnqueuer
}

// NewMockJobEnqueuer creates a new mock instance.
func NewMockJobEnqueuer(ctrl *gomock.Controller) *MockJobEnqueuer {
	mock := &MockJobEnqueuer{ctrl: ctrl}
	mock.recorder = &MockJobEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobEnqueuer) EXPECT() *MockJobEnqueuerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockJobEnqueuer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockJobEnqueuerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockJobEnqueuer)(nil).Close))
}

// Enqueue mocks base method.
func (m *MockJobEnqueuer) Enqueue(ctx context.Context, job interfaces.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockJobEnqueuerMockRecorder) Enqueue(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockJobEnqueuer)(nil).Enqueue), ctx, job)
}

// MockJobScheduler is a mock of JobScheduler interface.
type MockJobScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockJobSchedulerMockRecorder
	isgomock struct{}
}

// MockJobSchedulerMockRecorder is the mock recorder for MockJobScheduler.
type MockJobSchedulerMockRecorder struct {
	mock *MockJobScheduler
}

// NewMockJobScheduler creates a new mock instance.
func NewMockJobScheduler(ctrl *gomock.Controller) *MockJobScheduler {
	mock := &MockJobScheduler{ctrl: ctrl}
	mock.recorder = &MockJobSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobScheduler) EXPECT() *MockJobSchedulerMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockJobScheduler) Schedule(job interfaces.PeriodicJob, interval time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", job, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockJobSchedulerMockRecorder) Schedule(job, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockJobScheduler)(nil).Schedule), job, interval)
}

// MockWorkerRegistry is a mock of WorkerRegistry interface.
type MockWorkerRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRegistryMockRecorder
	isgomock struct{}
}

// MockWorkerRegistryMockRecorder is the mock recorder for MockWorkerRegistry.
type MockWorkerRegistryMockRecorder struct {
	mock *MockWorkerRegistry
}

// NewMockWorkerRegistry creates a new mock instance.
func NewMockWorkerRegistry(ctrl *gomock.Controller) *MockWorkerRegistry {
	mock := &MockWorkerRegistry{ctrl: ctrl}
	mock.recorder = &MockWorkerRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRegistry) EXPECT() *MockWorkerRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorkerRegistry) Get(kind string) (interfaces.Worker, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", kind)
	ret0, _ := ret[0].(interfaces.Worker)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkerRegistryMockRecorder) Get(kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkerRegistry)(nil).Get), kind)
}

// Register mocks base method.
func (m *MockWorkerRegistry) Register(kind string, worker interfaces.Worker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", kind, worker)
}

// Register indicates an expected call of Register.
func (mr *MockWorkerRegistryMockRecorder) Register(kind, worker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockWorkerRegistry)(nil).Register), kind, worker)
}
