// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Deduplicator)
//
// Generated by this command:
//
//	mockgen -destination=mock_dedup.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Deduplicator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeduplicator is a mock of Deduplicator interface.
type MockDeduplicator struct {
	ctrl     *gomock.Controller
	recorder *MockDeduplicatorMockRecorder
	isgomock struct{}
}

// MockDeduplicatorMockRecorder is the mock recorder for MockDeduplicator.
type MockDeduplicatorMockRecorder struct {
	mock *MockDeduplicator
}

// NewMockDeduplicator creates a new mock instance.
func NewMockDeduplicator(ctrl *gomock.Controller) *MockDeduplicator {
	mock := &MockDeduplicator{ctrl: ctrl}
	mock.recorder = &MockDeduplicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeduplicator) EXPECT() *MockDeduplicatorMockRecorder {
	return m.recorder
}

// Seen mocks base method.
func (m *MockDeduplicator) Seen(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seen", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seen indicates an expected call of Seen.
func (mr *MockDeduplicatorMockRecorder) Seen(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seen", reflect.TypeOf((*MockDeduplicator)(nil).Seen), ctx, key)
}
