// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Bulkhead)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_bulkhead.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Bulkhead
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBulkhead is a mock of Bulkhead interface.
type MockBulkhead struct {
	ctrl     *gomock.Controller
	recorder *MockBulkheadMockRecorder
	isgomock struct{}
}

// MockBulkheadMockRecorder is the mock recorder for MockBulkhead.
type MockBulkheadMockRecorder struct {
	mock *MockBulkhead
}

// NewMockBulkhead creates a new mock instance.
func NewMockBulkhead(ctrl *gomock.Controller) *MockBulkhead {
	mock := &MockBulkhead{ctrl: ctrl}
	mock.recorder = &MockBulkheadMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkhead) EXPECT() *MockBulkheadMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBulkhead) Execute(ctx context.Context, fn func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockBulkheadMockRecorder) Execute(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBulkhead)(nil).Execute), ctx, fn)
}

// TryExecute mocks base method.
func (m *MockBulkhead) TryExecute(fn func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryExecute", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryExecute indicates an expected call of TryExecute.
func (mr *MockBulkheadMockRecorder) TryExecute(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryExecute", reflect.TypeOf((*MockBulkhead)(nil).TryExecute), fn)
}
