// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: AnalyticsStore,AnalyticsCompactor,RowStream)
//
// Generated by this command:
//
//	mockgen -destination=mock_analytics.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces AnalyticsStore,AnalyticsCompactor,RowStream
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsStore is a mock of AnalyticsStore interface.
type MockAnalyticsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsStoreMockRecorder
	isgomock struct{}
}

// MockAnalyticsStoreMockRecorder is the mock recorder for MockAnalyticsStore.
type MockAnalyticsStoreMockRecorder struct {
	mock *MockAnalyticsStore
}

// NewMockAnalyticsStore creates a new mock instance.
func NewMockAnalyticsStore(ctrl *gomock.Controller) *MockAnalyticsStore {
	mock := &MockAnalyticsStore{ctrl: ctrl}
	mock.recorder = &MockAnalyticsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsStore) EXPECT() *MockAnalyticsStoreMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockAnalyticsStore) Aggregate(ctx context.Context, q types.AggregateQuery) (interfaces.RowStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, q)
	ret0, _ := ret[0].(interfaces.RowStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockAnalyticsStoreMockRecorder) Aggregate(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockAnalyticsStore)(nil).Aggregate), ctx, q)
}

// Start mocks base method.
func (m *MockAnalyticsStore) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAnalyticsStoreMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAnalyticsStore)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockAnalyticsStore) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAnalyticsStoreMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAnalyticsStore)(nil).Stop), ctx)
}

// Write mocks base method.
func (m *MockAnalyticsStore) Write(ctx context.Context, facts []types.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, facts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockAnalyticsStoreMockRecorder) Write(ctx, facts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockAnalyticsStore)(nil).Write), ctx, facts)
}

// MockAnalyticsCompactor is a mock of AnalyticsCompactor interface.
type MockAnalyticsCompactor struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsCompactorMockRecorder
	isgomock struct{}
}

// MockAnalyticsCompactorMockRecorder is the mock recorder for MockAnalyticsCompactor.
type MockAnalyticsCompactorMockRecorder struct {
	mock *MockAnalyticsCompactor
}

// NewMockAnalyticsCompactor creates a new mock instance.
func NewMockAnalyticsCompactor(ctrl *gomock.Controller) *MockAnalyticsCompactor {
	mock := &MockAnalyticsCompactor{ctrl: ctrl}
	mock.recorder = &MockAnalyticsCompactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsCompactor) EXPECT() *MockAnalyticsCompactorMockRecorder {
	return m.recorder
}

// Compact mocks base method.
func (m *MockAnalyticsCompactor) Compact(ctx context.Context, cube string, grain types.Grain, org string, bucket time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", ctx, cube, grain, org, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockAnalyticsCompactorMockRecorder) Compact(ctx, cube, grain, org, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockAnalyticsCompactor)(nil).Compact), ctx, cube, grain, org, bucket)
}

// MockRowStream is a mock of RowStream interface.
type MockRowStream struct {
	ctrl     *gomock.Controller
	recorder *MockRowStreamMockRecorder
	isgomock struct{}
}

// MockRowStreamMockRecorder is the mock recorder for MockRowStream.
type MockRowStreamMockRecorder struct {
	mock *MockRowStream
}

// NewMockRowStream creates a new mock instance.
func NewMockRowStream(ctrl *gomock.Controller) *MockRowStream {
	mock := &MockRowStream{ctrl: ctrl}
	mock.recorder = &MockRowStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowStream) EXPECT() *MockRowStreamMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRowStream) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRowStreamMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRowStream)(nil).Close))
}

// Next mocks base method.
func (m *MockRowStream) Next(ctx context.Context) ([]types.Row, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].([]types.Row)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Next indicates an expected call of Next.
func (mr *MockRowStreamMockRecorder) Next(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRowStream)(nil).Next), ctx)
}

// ResumeToken mocks base method.
func (m *MockRowStream) ResumeToken() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeToken")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ResumeToken indicates an expected call of ResumeToken.
func (mr *MockRowStreamMockRecorder) ResumeToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeToken", reflect.TypeOf((*MockRowStream)(nil).ResumeToken))
}
