// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: DeadLetterBackend)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_deadletter.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces DeadLetterBackend
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockDeadLetterBackend is a mock of DeadLetterBackend interface.
type MockDeadLetterBackend struct {
	ctrl     *gomock.Controller
	recorder *MockDeadLetterBackendMockRecorder
	isgomock struct{}
}

// MockDeadLetterBackendMockRecorder is the mock recorder for MockDeadLetterBackend.
type MockDeadLetterBackendMockRecorder struct {
	mock *MockDeadLetterBackend
}

// NewMockDeadLetterBackend creates a new mock instance.
func NewMockDeadLetterBackend(ctrl *gomock.Controller) *MockDeadLetterBackend {
	mock := &MockDeadLetterBackend{ctrl: ctrl}
	mock.recorder = &MockDeadLetterBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadLetterBackend) EXPECT() *MockDeadLetterBackendMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockDeadLetterBackend) Send(ctx context.Context, letter interfaces.DeadLetter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, letter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockDeadLetterBackendMockRecorder) Send(ctx, letter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDeadLetterBackend)(nil).Send), ctx, letter)
}
