// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: ExecutionObserver)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_observer.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces ExecutionObserver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionObserver is a mock of ExecutionObserver interface.
type MockExecutionObserver struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionObserverMockRecorder
	isgomock struct{}
}

// MockExecutionObserverMockRecorder is the mock recorder for MockExecutionObserver.
type MockExecutionObserverMockRecorder struct {
	mock *MockExecutionObserver
}

// NewMockExecutionObserver creates a new mock instance.
func NewMockExecutionObserver(ctrl *gomock.Controller) *MockExecutionObserver {
	mock := &MockExecutionObserver{ctrl: ctrl}
	mock.recorder = &MockExecutionObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionObserver) EXPECT() *MockExecutionObserverMockRecorder {
	return m.recorder
}

// OnGateComplete mocks base method.
func (m *MockExecutionObserver) OnGateComplete(gateName string, results types.StepResults, elapsed time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnGateComplete", gateName, results, elapsed)
}

// OnGateComplete indicates an expected call of OnGateComplete.
func (mr *MockExecutionObserverMockRecorder) OnGateComplete(gateName, results, elapsed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnGateComplete", reflect.TypeOf((*MockExecutionObserver)(nil).OnGateComplete), gateName, results, elapsed)
}

// OnGateStart mocks base method.
func (m *MockExecutionObserver) OnGateStart(name string, phases []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnGateStart", name, phases)
}

// OnGateStart indicates an expected call of OnGateStart.
func (mr *MockExecutionObserverMockRecorder) OnGateStart(name, phases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnGateStart", reflect.TypeOf((*MockExecutionObserver)(nil).OnGateStart), name, phases)
}

// OnPhaseComplete mocks base method.
func (m *MockExecutionObserver) OnPhaseComplete(name string, results types.StepResults, elapsed time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPhaseComplete", name, results, elapsed)
}

// OnPhaseComplete indicates an expected call of OnPhaseComplete.
func (mr *MockExecutionObserverMockRecorder) OnPhaseComplete(name, results, elapsed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPhaseComplete", reflect.TypeOf((*MockExecutionObserver)(nil).OnPhaseComplete), name, results, elapsed)
}

// OnPhaseStart mocks base method.
func (m *MockExecutionObserver) OnPhaseStart(name string, jobs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPhaseStart", name, jobs)
}

// OnPhaseStart indicates an expected call of OnPhaseStart.
func (mr *MockExecutionObserverMockRecorder) OnPhaseStart(name, jobs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPhaseStart", reflect.TypeOf((*MockExecutionObserver)(nil).OnPhaseStart), name, jobs)
}

// OnStepComplete mocks base method.
func (m *MockExecutionObserver) OnStepComplete(result types.StepResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStepComplete", result)
}

// OnStepComplete indicates an expected call of OnStepComplete.
func (mr *MockExecutionObserverMockRecorder) OnStepComplete(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStepComplete", reflect.TypeOf((*MockExecutionObserver)(nil).OnStepComplete), result)
}

// OnStepStart mocks base method.
func (m *MockExecutionObserver) OnStepStart(name, group string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStepStart", name, group)
}

// OnStepStart indicates an expected call of OnStepStart.
func (mr *MockExecutionObserverMockRecorder) OnStepStart(name, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStepStart", reflect.TypeOf((*MockExecutionObserver)(nil).OnStepStart), name, group)
}
