// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: MessagePublisher,CountingPublisher,MessageConsumer,DynamicConsumer,PatternConsumer)
//
// Generated by this command:
//
//	mockgen -destination=mock_messaging.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces MessagePublisher,CountingPublisher,MessageConsumer,DynamicConsumer,PatternConsumer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
	isgomock struct{}
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockMessagePublisher) Publish(ctx context.Context, topic string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockMessagePublisherMockRecorder) Publish(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockMessagePublisher)(nil).Publish), ctx, topic, payload)
}

// PublishBatch mocks base method.
func (m *MockMessagePublisher) PublishBatch(ctx context.Context, topic string, payloads [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatch", ctx, topic, payloads)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatch indicates an expected call of PublishBatch.
func (mr *MockMessagePublisherMockRecorder) PublishBatch(ctx, topic, payloads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatch", reflect.TypeOf((*MockMessagePublisher)(nil).PublishBatch), ctx, topic, payloads)
}

// MockCountingPublisher is a mock of CountingPublisher interface.
type MockCountingPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockCountingPublisherMockRecorder
	isgomock struct{}
}

// MockCountingPublisherMockRecorder is the mock recorder for MockCountingPublisher.
type MockCountingPublisherMockRecorder struct {
	mock *MockCountingPublisher
}

// NewMockCountingPublisher creates a new mock instance.
func NewMockCountingPublisher(ctrl *gomock.Controller) *MockCountingPublisher {
	mock := &MockCountingPublisher{ctrl: ctrl}
	mock.recorder = &MockCountingPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountingPublisher) EXPECT() *MockCountingPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockCountingPublisher) Publish(ctx context.Context, topic string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockCountingPublisherMockRecorder) Publish(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCountingPublisher)(nil).Publish), ctx, topic, payload)
}

// PublishBatch mocks base method.
func (m *MockCountingPublisher) PublishBatch(ctx context.Context, topic string, payloads [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBatch", ctx, topic, payloads)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBatch indicates an expected call of PublishBatch.
func (mr *MockCountingPublisherMockRecorder) PublishBatch(ctx, topic, payloads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatch", reflect.TypeOf((*MockCountingPublisher)(nil).PublishBatch), ctx, topic, payloads)
}

// PublishCount mocks base method.
func (m *MockCountingPublisher) PublishCount(ctx context.Context, topic string, payload []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCount", ctx, topic, payload)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishCount indicates an expected call of PublishCount.
func (mr *MockCountingPublisherMockRecorder) PublishCount(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCount", reflect.TypeOf((*MockCountingPublisher)(nil).PublishCount), ctx, topic, payload)
}

// MockMessageConsumer is a mock of MessageConsumer interface.
type MockMessageConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageConsumerMockRecorder
	isgomock struct{}
}

// MockMessageConsumerMockRecorder is the mock recorder for MockMessageConsumer.
type MockMessageConsumerMockRecorder struct {
	mock *MockMessageConsumer
}

// NewMockMessageConsumer creates a new mock instance.
func NewMockMessageConsumer(ctrl *gomock.Controller) *MockMessageConsumer {
	mock := &MockMessageConsumer{ctrl: ctrl}
	mock.recorder = &MockMessageConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageConsumer) EXPECT() *MockMessageConsumerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessageConsumer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessageConsumerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessageConsumer)(nil).Close))
}

// Subscribe mocks base method.
func (m *MockMessageConsumer) Subscribe(ctx context.Context, topic string, handler interfaces.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topic, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMessageConsumerMockRecorder) Subscribe(ctx, topic, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageConsumer)(nil).Subscribe), ctx, topic, handler)
}

// MockDynamicConsumer is a mock of DynamicConsumer interface.
type MockDynamicConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicConsumerMockRecorder
	isgomock struct{}
}

// MockDynamicConsumerMockRecorder is the mock recorder for MockDynamicConsumer.
type MockDynamicConsumerMockRecorder struct {
	mock *MockDynamicConsumer
}

// NewMockDynamicConsumer creates a new mock instance.
func NewMockDynamicConsumer(ctrl *gomock.Controller) *MockDynamicConsumer {
	mock := &MockDynamicConsumer{ctrl: ctrl}
	mock.recorder = &MockDynamicConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicConsumer) EXPECT() *MockDynamicConsumerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDynamicConsumer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDynamicConsumerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDynamicConsumer)(nil).Close))
}

// Subscribe mocks base method.
func (m *MockDynamicConsumer) Subscribe(ctx context.Context, topic string, handler interfaces.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topic, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockDynamicConsumerMockRecorder) Subscribe(ctx, topic, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockDynamicConsumer)(nil).Subscribe), ctx, topic, handler)
}

// Unsubscribe mocks base method.
func (m *MockDynamicConsumer) Unsubscribe(ctx context.Context, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockDynamicConsumerMockRecorder) Unsubscribe(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockDynamicConsumer)(nil).Unsubscribe), ctx, topic)
}

// MockPatternConsumer is a mock of PatternConsumer interface.
type MockPatternConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockPatternConsumerMockRecorder
	isgomock struct{}
}

// MockPatternConsumerMockRecorder is the mock recorder for MockPatternConsumer.
type MockPatternConsumerMockRecorder struct {
	mock *MockPatternConsumer
}

// NewMockPatternConsumer creates a new mock instance.
func NewMockPatternConsumer(ctrl *gomock.Controller) *MockPatternConsumer {
	mock := &MockPatternConsumer{ctrl: ctrl}
	mock.recorder = &MockPatternConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatternConsumer) EXPECT() *MockPatternConsumerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPatternConsumer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPatternConsumerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPatternConsumer)(nil).Close))
}

// PSubscribe mocks base method.
func (m *MockPatternConsumer) PSubscribe(ctx context.Context, pattern string, handler interfaces.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PSubscribe", ctx, pattern, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// PSubscribe indicates an expected call of PSubscribe.
func (mr *MockPatternConsumerMockRecorder) PSubscribe(ctx, pattern, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PSubscribe", reflect.TypeOf((*MockPatternConsumer)(nil).PSubscribe), ctx, pattern, handler)
}

// PUnsubscribe mocks base method.
func (m *MockPatternConsumer) PUnsubscribe(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PUnsubscribe", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// PUnsubscribe indicates an expected call of PUnsubscribe.
func (mr *MockPatternConsumerMockRecorder) PUnsubscribe(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUnsubscribe", reflect.TypeOf((*MockPatternConsumer)(nil).PUnsubscribe), ctx, pattern)
}

// Subscribe mocks base method.
func (m *MockPatternConsumer) Subscribe(ctx context.Context, topic string, handler interfaces.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topic, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPatternConsumerMockRecorder) Subscribe(ctx, topic, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPatternConsumer)(nil).Subscribe), ctx, topic, handler)
}

// Unsubscribe mocks base method.
func (m *MockPatternConsumer) Unsubscribe(ctx context.Context, topic string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockPatternConsumerMockRecorder) Unsubscribe(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockPatternConsumer)(nil).Unsubscribe), ctx, topic)
}
