// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: OrgProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_org_provider.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces OrgProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/gt-tech-ai/knowledge-engine/go/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgProvider is a mock of OrgProvider interface.
type MockOrgProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOrgProviderMockRecorder
	isgomock struct{}
}

// MockOrgProviderMockRecorder is the mock recorder for MockOrgProvider.
type MockOrgProviderMockRecorder struct {
	mock *MockOrgProvider
}

// NewMockOrgProvider creates a new mock instance.
func NewMockOrgProvider(ctrl *gomock.Controller) *MockOrgProvider {
	mock := &MockOrgProvider{ctrl: ctrl}
	mock.recorder = &MockOrgProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgProvider) EXPECT() *MockOrgProviderMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrgProvider) CreateOrganization(ctx context.Context, org types.OrgWrite) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrgProviderMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrgProvider)(nil).CreateOrganization), ctx, org)
}

// DeleteInvitation mocks base method.
func (m *MockOrgProvider) DeleteInvitation(ctx context.Context, orgExtID, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, orgExtID, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockOrgProviderMockRecorder) DeleteInvitation(ctx, orgExtID, invitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockOrgProvider)(nil).DeleteInvitation), ctx, orgExtID, invitationID)
}

// DeleteOrganization mocks base method.
func (m *MockOrgProvider) DeleteOrganization(ctx context.Context, orgExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, orgExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockOrgProviderMockRecorder) DeleteOrganization(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockOrgProvider)(nil).DeleteOrganization), ctx, orgExtID)
}

// InviteMembers mocks base method.
func (m *MockOrgProvider) InviteMembers(ctx context.Context, orgExtID string, invites []types.InviteInput) map[string]error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteMembers", ctx, orgExtID, invites)
	ret0, _ := ret[0].(map[string]error)
	return ret0
}

// InviteMembers indicates an expected call of InviteMembers.
func (mr *MockOrgProviderMockRecorder) InviteMembers(ctx, orgExtID, invites any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMembers", reflect.TypeOf((*MockOrgProvider)(nil).InviteMembers), ctx, orgExtID, invites)
}

// ListInvitations mocks base method.
func (m *MockOrgProvider) ListInvitations(ctx context.Context, orgExtID string) ([]types.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx, orgExtID)
	ret0, _ := ret[0].([]types.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockOrgProviderMockRecorder) ListInvitations(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockOrgProvider)(nil).ListInvitations), ctx, orgExtID)
}

// ListOrganizationMembers mocks base method.
func (m *MockOrgProvider) ListOrganizationMembers(ctx context.Context, orgExtID string) ([]types.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationMembers", ctx, orgExtID)
	ret0, _ := ret[0].([]types.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMembers indicates an expected call of ListOrganizationMembers.
func (mr *MockOrgProviderMockRecorder) ListOrganizationMembers(ctx, orgExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMembers", reflect.TypeOf((*MockOrgProvider)(nil).ListOrganizationMembers), ctx, orgExtID)
}

// ListOrganizations mocks base method.
func (m *MockOrgProvider) ListOrganizations(ctx context.Context) ([]types.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]types.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrgProviderMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrgProvider)(nil).ListOrganizations), ctx)
}

// RemoveOrganizationMember mocks base method.
func (m *MockOrgProvider) RemoveOrganizationMember(ctx context.Context, orgExtID, userExtID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOrganizationMember", ctx, orgExtID, userExtID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOrganizationMember indicates an expected call of RemoveOrganizationMember.
func (mr *MockOrgProviderMockRecorder) RemoveOrganizationMember(ctx, orgExtID, userExtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOrganizationMember", reflect.TypeOf((*MockOrgProvider)(nil).RemoveOrganizationMember), ctx, orgExtID, userExtID)
}

// UpdateOrganization mocks base method.
func (m *MockOrgProvider) UpdateOrganization(ctx context.Context, org types.OrgWrite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockOrgProviderMockRecorder) UpdateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockOrgProvider)(nil).UpdateOrganization), ctx, org)
}
