// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Retrier)
//
// Generated by this command:
//
//	mockgen -destination=mock_retrier.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Retrier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRetrier is a mock of Retrier interface.
type MockRetrier struct {
	ctrl     *gomock.Controller
	recorder *MockRetrierMockRecorder
	isgomock struct{}
}

// MockRetrierMockRecorder is the mock recorder for MockRetrier.
type MockRetrierMockRecorder struct {
	mock *MockRetrier
}

// NewMockRetrier creates a new mock instance.
func NewMockRetrier(ctrl *gomock.Controller) *MockRetrier {
	mock := &MockRetrier{ctrl: ctrl}
	mock.recorder = &MockRetrierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetrier) EXPECT() *MockRetrierMockRecorder {
	return m.recorder
}

// Retry mocks base method.
func (m *MockRetrier) Retry(ctx context.Context, op func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", ctx, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockRetrierMockRecorder) Retry(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockRetrier)(nil).Retry), ctx, op)
}
