// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gt-tech-ai/knowledge-engine/go/core/interfaces (interfaces: Metrics,Counter,Histogram,Gauge)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/mocks/mock_metrics.go -package=mocks github.com/gt-tech-ai/knowledge-engine/go/core/interfaces Metrics,Counter,Histogram,Gauge
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	interfaces "github.com/gt-tech-ai/knowledge-engine/go/core/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// Counter mocks base method.
func (m *MockMetrics) Counter(name, help string, labels ...string) interfaces.Counter {
	m.ctrl.T.Helper()
	varargs := []any{name, help}
	for _, a := range labels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Counter", varargs...)
	ret0, _ := ret[0].(interfaces.Counter)
	return ret0
}

// Counter indicates an expected call of Counter.
func (mr *MockMetricsMockRecorder) Counter(name, help any, labels ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, help}, labels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counter", reflect.TypeOf((*MockMetrics)(nil).Counter), varargs...)
}

// Gauge mocks base method.
func (m *MockMetrics) Gauge(name, help string, labels ...string) interfaces.Gauge {
	m.ctrl.T.Helper()
	varargs := []any{name, help}
	for _, a := range labels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Gauge", varargs...)
	ret0, _ := ret[0].(interfaces.Gauge)
	return ret0
}

// Gauge indicates an expected call of Gauge.
func (mr *MockMetricsMockRecorder) Gauge(name, help any, labels ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, help}, labels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockMetrics)(nil).Gauge), varargs...)
}

// Handler mocks base method.
func (m *MockMetrics) Handler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Handler indicates an expected call of Handler.
func (mr *MockMetricsMockRecorder) Handler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockMetrics)(nil).Handler))
}

// Histogram mocks base method.
func (m *MockMetrics) Histogram(name, help string, buckets []float64, labels ...string) interfaces.Histogram {
	m.ctrl.T.Helper()
	varargs := []any{name, help, buckets}
	for _, a := range labels {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Histogram", varargs...)
	ret0, _ := ret[0].(interfaces.Histogram)
	return ret0
}

// Histogram indicates an expected call of Histogram.
func (mr *MockMetricsMockRecorder) Histogram(name, help, buckets any, labels ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, help, buckets}, labels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Histogram", reflect.TypeOf((*MockMetrics)(nil).Histogram), varargs...)
}

// MockCounter is a mock of Counter interface.
type MockCounter struct {
	ctrl     *gomock.Controller
	recorder *MockCounterMockRecorder
	isgomock struct{}
}

// MockCounterMockRecorder is the mock recorder for MockCounter.
type MockCounterMockRecorder struct {
	mock *MockCounter
}

// NewMockCounter creates a new mock instance.
func NewMockCounter(ctrl *gomock.Controller) *MockCounter {
	mock := &MockCounter{ctrl: ctrl}
	mock.recorder = &MockCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounter) EXPECT() *MockCounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCounter) Add(value float64, labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockCounterMockRecorder) Add(value any, labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, labelValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCounter)(nil).Add), varargs...)
}

// Inc mocks base method.
func (m *MockCounter) Inc(labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockCounterMockRecorder) Inc(labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockCounter)(nil).Inc), labelValues...)
}

// MockHistogram is a mock of Histogram interface.
type MockHistogram struct {
	ctrl     *gomock.Controller
	recorder *MockHistogramMockRecorder
	isgomock struct{}
}

// MockHistogramMockRecorder is the mock recorder for MockHistogram.
type MockHistogramMockRecorder struct {
	mock *MockHistogram
}

// NewMockHistogram creates a new mock instance.
func NewMockHistogram(ctrl *gomock.Controller) *MockHistogram {
	mock := &MockHistogram{ctrl: ctrl}
	mock.recorder = &MockHistogramMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistogram) EXPECT() *MockHistogramMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockHistogram) Observe(value float64, labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Observe", varargs...)
}

// Observe indicates an expected call of Observe.
func (mr *MockHistogramMockRecorder) Observe(value any, labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, labelValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockHistogram)(nil).Observe), varargs...)
}

// MockGauge is a mock of Gauge interface.
type MockGauge struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeMockRecorder
	isgomock struct{}
}

// MockGaugeMockRecorder is the mock recorder for MockGauge.
type MockGaugeMockRecorder struct {
	mock *MockGauge
}

// NewMockGauge creates a new mock instance.
func NewMockGauge(ctrl *gomock.Controller) *MockGauge {
	mock := &MockGauge{ctrl: ctrl}
	mock.recorder = &MockGaugeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGauge) EXPECT() *MockGaugeMockRecorder {
	return m.recorder
}

// Dec mocks base method.
func (m *MockGauge) Dec(labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Dec", varargs...)
}

// Dec indicates an expected call of Dec.
func (mr *MockGaugeMockRecorder) Dec(labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dec", reflect.TypeOf((*MockGauge)(nil).Dec), labelValues...)
}

// Inc mocks base method.
func (m *MockGauge) Inc(labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockGaugeMockRecorder) Inc(labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockGauge)(nil).Inc), labelValues...)
}

// Set mocks base method.
func (m *MockGauge) Set(value float64, labelValues ...string) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range labelValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Set", varargs...)
}

// Set indicates an expected call of Set.
func (mr *MockGaugeMockRecorder) Set(value any, labelValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, labelValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockGauge)(nil).Set), varargs...)
}
